=== abocadev/dam/M04 - Lenguajes de Marcas/UF 2/UF2-ACT2/pregunta3.dtd
<!ELEMENT cd (coche, coche, coche)>
<!ELEMENT coche (codigoCoche, marca, modelo, matricula, potencia, plazas, numeroPuertas)>
<!ELEMENT codigoCoche (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT potencia (#PCDATA)>
<!ELEMENT plazas (#PCDATA)>
<!ELEMENT numeroPuertas (#PCDATA)>

<!ATTLIST potencia medida NMTOKEN #REQUIRED>

=== abocadev/dam/M04 - Lenguajes de Marcas/UF 2/UF2-ACT2/pregunta3.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "pregunta3.dtd">
<cd>
    <coche>
        <codigoCoche>00123</codigoCoche>
        <marca>Opel</marca>
        <modelo>Corsa</modelo>
        <matricula>0527CSP</matricula>
        <potencia medida="caballos">1000</potencia>
        <plazas>5</plazas>
        <numeroPuertas>5</numeroPuertas>
    </coche>
    <coche>
        <codigoCoche>00123</codigoCoche>
        <marca>Opel</marca>
        <modelo>Corsa</modelo>
        <matricula>0527CSP</matricula>
        <potencia medida="caballos">1000</potencia>
        <plazas>5</plazas>
        <numeroPuertas>5</numeroPuertas>
    </coche>
    <coche>
        <codigoCoche>00123</codigoCoche>
        <marca>Opel</marca>
        <modelo>Corsa</modelo>
        <matricula>0527CSP</matricula>
        <potencia medida="caballos">1000</potencia>
        <plazas>5</plazas>
        <numeroPuertas>5</numeroPuertas>
    </coche>
</cd>
