=== abocadev/dam/M04 - Lenguajes de Marcas/UF 2/UF2-ACT2/pregunta2.dtd
<!ELEMENT cd (evento, evento, evento)>
<!ELEMENT evento (fecha, nombreeven, ubicacion, participantes)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT nombreeven (#PCDATA)>
<!ELEMENT ubicacion (#PCDATA)>
<!ELEMENT participantes (#PCDATA)>

<!ATTLIST evento modalidad NMTOKEN #REQUIRED>
<!ATTLIST fecha formato CDATA #REQUIRED>

=== abocadev/dam/M04 - Lenguajes de Marcas/UF 2/UF2-ACT2/pregunta2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cd SYSTEM "pregunta2.dtd">
<cd>
    <evento modalidad="presencial">
        <fecha formato="dia/mes/hora">13/01/2022</fecha>
        <nombreeven>Hackaton Barcelona</nombreeven>
        <ubicacion>Barcelona, España</ubicacion>
        <participantes>1000</participantes>
    </evento>
    <evento modalidad="online">
        <fecha formato="dia/mes/hora">25/03/2022</fecha>
        <nombreeven>Hackaton Nuwe</nombreeven>
        <ubicacion>España</ubicacion>
        <participantes>2000</participantes>
    </evento>
    <evento modalidad="online">
        <fecha formato="dia/mes/hora">24/10/2022</fecha>
        <nombreeven>Hackaton de FP</nombreeven>
        <ubicacion>Barcelona, España</ubicacion>
        <participantes>100</participantes>
    </evento>
</cd>
